# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jan Lucca Thümmel
title: Student
email:
website: https://plotozypresse.github.io

# Dark Mode (true/false/never)
darkmode: True

# Social links
#twitter_username: facespics
github_username: PlotoZypresse
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: janthuemmel
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "G-M29H8DVFE2"
google_analytics: "G-M29H8DVFE2"

# About Section
# about_title: About Me
about_profile_image: images/cvpic2.jpeg
about_content: | # this will include new lines to allow paragraphs
  My name is Jan, I am 23 years old, and I am currently studying Computer Science at the University of Southern Denmark.
  I will finish my 4th semester this June.
  After completing my Bachelor's degree, I plan to continue with my Master's degree in Computer Science.
  Besides studying I love to run, spend time with friends and if the weather is great during the summer months I like to ride my bike.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Bank System
        link: https://github.com/PlotoZypresse/BankingSystem
        # link_text: Project Website
        additional_links:
          - title: Bank System
            icon: fab fa-github
            url: https://github.com/PlotoZypresse/BankingSystem
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project after taking a course on system architecture at university, where C programming was included. I was fascinated by C and decided to start my own project after the course concluded.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Citti-Markt Flensburg
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: July 2020 - August 2021
        # quote: >

        description: | # this will include new lines to allow paragraphs
          I worked in retail during my gap year to save money for traveling. Sadly, I did not travel because of COVID.

      - layout: left
        title: Förde-Show Concept Flensburg
        caption: May 2019 - April 2020

        description: | # this will include new lines to allow paragraphs
          During my time in high school, I worked at Förde Show Concept, a company founded in 1992 and operating as a full-service agency in the field of events, catering, and concerts.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Southern Denmark
        caption: 2022 - 2025
        sub_title: BSc Computer Science
        # quote: >

        description: | # this will include new lines to allow paragraphs
          I am currently pursueing a Bachelor of Science degree in Computer Science. The program provided me with a solid foundation in various aspects of computer science, including algorithms, programming languages, data structures, and software engineering principles.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computers and software some of my other interests and hobbies are:
      - Running
      - Gaming
      - Cycling

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
